# Generated by Django 4.2.2 on 2024-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                auto_now=True, verbose_name="дата начала рассылки"
            ),
        ),
    ]
