# Generated by Django 4.2.2 on 2024-10-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_client_owner_alter_mailing_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="message",
            name="owner",
        ),
    ]
