# Generated by Django 4.2.2 on 2024-11-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_alter_mailing_options_mailing_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Активна"),
                    ("completed", "Завершена"),
                    ("disabled", "Отключить"),
                ],
                default="created",
                max_length=10,
                verbose_name="статус",
            ),
        ),
    ]
